name: Python application

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: Running Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test Person
      run: python -m unittest test.test_person
      id: ID_Person
    - name: Test Fibonacci
      run: python -m unittest test.test_fib_generator
      id: ID_Fibonacci
